apiVersion: v1
kind: Service
metadata:
  name: k8stimeservicewithhealthcheck2-service
spec:
  type: NodePort
  selector:
    app: k8stimeservicewithhealthcheck2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
